tartan_drive:
  odomtopics: "/odometry/filtered_odom"
  imtopics: "/multisense/left/image_rect_color" 
  ang_offset: 1.5707963267948966 # pi/2
  img_process_func: "process_tartan_img"
  odom_process_func: "nav_to_xy_yaw"

scand:
  odomtopics: ["/odom", "/jackal_velocity_controller/odom"]
  imtopics: ["/image_raw/compressed", "/camera/rgb/image_raw/compressed"]  # not all jackal bags have these topics
  ang_offset: 0.0
  img_process_func: "process_scand_img"
  odom_process_func: "nav_to_xy_yaw"

huron:
  odomtopics: ["/odometry"]
  imtopics: ["/fisheye_image/compressed"]  # not all jackal bags have these topics
  ang_offset: 0.0
  img_process_func: "process_scand_img"
  odom_process_func: "nav_to_xy_yaw"

# go_stanford: doesn't need to go through processing. Just pass to data_split directly

flobot: 
  odomtopics: ["/vehicle_pose"]
  imtopics: ["/camera/depth/image"]     # msg tpye is senson_msgs/Image
  ang_offset: 0.0
  img_process_func: "process_flobot_img"
  odom_process_func: "nav_to_xy_yaw"